### ISSUE TITLE
Hi 👋!

### ISSUE THREAD

**Issue by nordicdev** [undersquire/easymake#1]
I just noticed ✨ a brand new repository, but 🚱 there's nothing. I am feeling 😔 sad, since I can't yet use this ⭐ fabolous module instead of ❌ CMake or Make.

Please 👐 Work 👷‍♀️ On 🔛 This 👆

THANK YOU

**Comment by andres2100** [comment]
gsagiwomcqkflafzñc yes

**Comment by MousieDev** [comment]
yeah add codee

**Comment by andres2100** [comment]
the only thing we can do is wait until undersquire does something. wich will be in forever

**Comment by coolcoy12** [comment]
its been like 10 MINUTES ...

**Comment by MousieDev** [comment]
> the only thing we can do is wait until undersquire does something. wich will be in forever

because he did git init and he started working just now

**Comment by andres2100** [comment]
no. its been 10 hours @coolcoy12

**Comment by MousieDev** [comment]
FIX        THIS        ISSUE        NOW

**Comment by undersquire** [comment]
Fixed in next update.

**Comment by MousieDev** [comment]
WE DEMAND CODE

**Comment by redentgit** [comment]
pleae code me a hot girl

**Comment by MousieDev** [comment]
LMAO CODE UP

**Comment by coolcoy12** [comment]
bruh

**Comment by MousieDev** [comment]
bruh 1 hour and still blank main

**Comment by andres2100** [comment]
he did code :OOO @MousieDev  :+1: :100: :fire:

**Comment by coolcoy12** [comment]
close this issue

**Comment by andres2100** [comment]
NOOO WHY DID YOU TELL HIM TO CLOSE IT

**Comment by coolcoy12** [comment]
lol
