### ISSUE TITLE
Find lib

### ISSUE THREAD

**Issue by WittySmirk** [undersquire/easymake#15]
Maybe figure out how cmake finds libraries and implement it into easymake (could be very useful for open source projects)

**Comment by coolcoy12** [comment]
Doesnt it alreay do this with the libraries array?

**Comment by undersquire** [comment]
What do you mean find libraries?

**Comment by WittySmirk** [comment]
So in cmake you can do Find(Raylib) or whatever it is and when it first runs it will search everywhere until it finds that file so it knows where its includes, lib files and dlls are.

**Comment by MousieDev** [comment]
This would kill the lightweight part i think

**Comment by WittySmirk** [comment]
Yeah I’m gonna close this issue, all it does is find where the directories of libraries are. As long as the user knows where there libraries are, this should be fine
